{% set name = "cxroots" %}
{% set version = "3.1.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/cxroots-{{ version }}.tar.gz
  sha256: ead64a95439e66128a027901fccb4c9c3953620336206ad18d9ac8513bada5b9

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv
  number: 0

requirements:
  host:
    - pip
    - pytest-runner
    - python >=3.10
  run:
    - mpmath
    - numpy
    - numpydoc
    - python >=3.10
    - scipy
    - rich

test:
  imports:
    - cxroots
    - cxroots.tests
    - cxroots.contours
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://rparini.github.io/cxroots/
  summary: Find all the roots (zeros) of a complex analytic function within a given contour in the complex plane.
  license: BSD-3-Clause
  license_family: BSD
  license_file: LICENSE
  doc_url: https://rparini.github.io/cxroots/
  dev_url: https://github.com/rparini/cxroots

extra:
  recipe-maintainers:
    - petar-andrejic
