{% set name = "cxroots" %}
{% set version = "3.0.1" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/cxroots-{{ version }}.tar.gz
  sha256: 1665a222314483aa85e61bbffc789ea72da1e3c4414be9fa7854e40610b83213

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv
  number: 0

requirements:
  host:
    - pip
    - pytest-runner
    - python >=3.6
  run:
    - mpmath
    - numdifftools >=0.9.39
    - numpy <1.25
    - numpydoc
    - python >=3.6
    - scipy
    - rich

test:
  imports:
    - cxroots
    - cxroots.tests
    - cxroots.contours
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://rparini.github.io/cxroots/
  summary: Find all the roots (zeros) of a complex analytic function within a given contour in the complex plane.
  license: BSD-3-Clause
  license_family: BSD
  license_file: LICENSE
  doc_url: https://rparini.github.io/cxroots/
  dev_url: https://github.com/rparini/cxroots

extra:
  recipe-maintainers:
    - petar-andrejic
