{% set name = "cxroots" %}
{% set version = "2.0.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/cxroots-{{ version }}.tar.gz
  sha256: 2fe93c30b16b6db0b43374238aa235745807bde7f63793a40d5e2c058815f680

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv
  number: 0

requirements:
  host:
    - pip
    - pytest-runner
    - python >=3.6
  run:
    - mpmath
    - numdifftools >=0.9.39
    - numpy
    - numpydoc
    - python >=3.6
    - scipy

test:
  imports:
    - cxroots
    - cxroots.tests
    - cxroots.contours
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://rparini.github.io/cxroots/
  summary: Find all the roots (zeros) of a complex analytic function within a given contour in the complex plane.
  license: BSD-3-Clause
  license_family: BSD
  license_file: LICENSE
  doc_url: https://rparini.github.io/cxroots/
  dev_url: https://github.com/rparini/cxroots

extra:
  recipe-maintainers:
    - petar-andrejic
